# Generated by Django 5.0.3 on 2024-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_price",
            new_name="quantity_bought",
        ),
        migrations.AddField(
            model_name="order",
            name="cost_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="selling_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
