# Generated by Django 5.0.3 on 2024-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_rename_total_price_order_quantity_bought_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="profit",
            field=models.FloatField(null=True),
        ),
    ]
