# Generated by Django 5.0.3 on 2024-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_procurement_officer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="quantity_bought",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
