# Generated by Django 5.0.3 on 2024-03-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_order_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
    ]
