# Generated by Django 5.0.3 on 2024-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="procurement_officer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
